language: php

env:
  global:
    - setup=stable
    - REDIS_HOST=127.0.0.1
    - REDIS_PORT=6379
    - REDIS_CLUSTER_HOST_1=127.0.0.1
    - REDIS_CLUSTER_HOST_2=127.0.0.1
    - REDIS_CLUSTER_HOST_3=127.0.0.1
    - REDIS_CLUSTER_PORT_1=8000
    - REDIS_CLUSTER_PORT_2=8001
    - REDIS_CLUSTER_PORT_3=8002
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

before_install:
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

  - wget http://download.redis.io/releases/redis-4.0.9.tar.gz
  - tar xzf redis-4.0.9.tar.gz
  - cd redis-4.0.9
  - make
  - sudo make PREFIX=/var/lib/redis install
  - sudo cp src/redis-trib.rb /var/lib/redis/
  - sudo mkdir -p /var/lib/redis/cluster/{8000,8001,8002}
  - echo "port {port}" > ./redis-cluster.conf
  - echo "dir /var/lib/redis/cluster/{port}" >> ./redis-cluster.conf
  - echo "cluster-enabled yes" >> ./redis-cluster.conf
  - echo "daemonize yes" >> ./redis-cluster.conf
  - sudo chmod -R 777 /var/lib/redis
  - sed 's/{port}/8000/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-8000.conf
  - sed 's/{port}/8001/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-8001.conf
  - sed 's/{port}/8002/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-8002.conf

  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-8000.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-8001.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-8002.conf
  - sudo /var/lib/redis/redis-trib.rb create  --replicas  1 127.0.0.1:8000 127.0.0.1:8001 127.0.0.1:8002
  - sudo rm -rf redis-4.0.9 redis-4.0.9.tar.gz

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi




script: cd build && ../vendor/bin/phpunit
