language: php

env:
  global:
    - setup=stable
    - REDIS_HOST=127.0.0.1
    - REDIS_PORT=6379
    - REDIS_CLUSTER_HOST_1=127.0.0.1
    - REDIS_CLUSTER_HOST_2=127.0.0.1
    - REDIS_CLUSTER_HOST_3=127.0.0.1
    - REDIS_CLUSTER_HOST_4=127.0.0.1
    - REDIS_CLUSTER_HOST_5=127.0.0.1
    - REDIS_CLUSTER_HOST_6=127.0.0.1
    - REDIS_CLUSTER_PORT_1=10001
    - REDIS_CLUSTER_PORT_2=10002
    - REDIS_CLUSTER_PORT_3=10003
    - REDIS_CLUSTER_PORT_4=10004
    - REDIS_CLUSTER_PORT_5=10005
    - REDIS_CLUSTER_PORT_6=10006

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

before_install:
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

  - gem install redis
  - wget http://download.redis.io/releases/redis-4.0.9.tar.gz
  - tar xzf redis-4.0.9.tar.gz
  - cd redis-4.0.9
  - make
  - sudo make PREFIX=/var/lib/redis install
  - sudo cp src/redis-trib.rb /var/lib/redis/
  - sudo mkdir -p /var/lib/redis/cluster/{10001,10002,10003,10004,10005,10006}
  - echo "port {port}" > ./redis-cluster.conf
  - echo "bind 127.0.0.1" >> ./redis-cluster.conf
  - echo "dir /var/lib/redis/cluster/{port}" >> ./redis-cluster.conf
  - echo "cluster-enabled yes" >> ./redis-cluster.conf
  - echo "daemonize yes" >> ./redis-cluster.conf
  - sudo chmod -R 777 /var/lib/redis
  - sed 's/{port}/10001/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-10001.conf
  - sed 's/{port}/10002/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-10002.conf
  - sed 's/{port}/10003/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-10003.conf
  - sed 's/{port}/10004/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-10004.conf
  - sed 's/{port}/10005/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-10005.conf
  - sed 's/{port}/10006/' ./redis-cluster.conf > /var/lib/redis/redis-cluster-10006.conf
  - cd ../
  - sudo rm -rf redis-4.0.9 redis-4.0.9.tar.gz
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-10001.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-10002.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-10003.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-10004.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-10005.conf
  - sudo /var/lib/redis/bin/redis-server /var/lib/redis/redis-cluster-10006.conf
  - sudo echo "yes" | /var/lib/redis/redis-trib.rb create  --replicas  1 127.0.0.1:10001 127.0.0.1:10002 127.0.0.1:10003 127.0.0.1:10004 127.0.0.1:10005 127.0.0.1:10006

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - travis_retry php vendor/bin/phpunit -c build/phpunit.xml

after_success:
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - travis_retry php vendor/bin/php-coveralls -v
